import test from 'node:test';
import assert from 'node:assert/strict';
import {toggleDiverterDirection,diverterAllowsEdge,diverterProfile,advanceDiverterTransfer} from '../src/diverter.js';
import {CadFlowEngine} from '../src/engine.js';
import {validateFlowGraph} from '../src/flow-graph.js';
test('전체 이송 시퀀스에서 선택한 분기로만 배출하고 JSON 왕복 후 설정 유지',()=>{
  const source={id:'s',type:'source',parameters:{injectionInterval:3}},cv=conveyor(),up={id:'up',type:'sink',x:0,y:-100,parameters:{dischargeTime:.1}},down={id:'down',type:'sink',x:0,y:100};
  const layout=JSON.parse(JSON.stringify({equipment:[source,cv,up,down],cargoSpec:{length:500,width:400,unit:'mm'},cadSchematic:{edges:[{from:'s',to:'cv',toPort:'left'},{from:'cv',to:'up',fromPort:'top'},{from:'cv',to:'down',fromPort:'bottom'}]}}));
  const engine=new CadFlowEngine(layout,{simDuration:60});for(let i=0;i<3000;i++)engine.step(.02);
  assert.ok(engine.state.completedProducts.length>1);assert.equal(engine.state.events.some(event=>event.type==='sensor-infeed'&&event.equipmentId==='down'),false);
  const arrivals=engine.state.events.filter(event=>event.type==='sensor-infeed'&&event.equipmentId==='up');assert.ok(arrivals.length>1);
});
const conveyor=()=>({id:'cv',type:'conveyor',x:0,y:0,parameters:{length:5,speed:1,diverterEnabled:1,diverterDirections:['up'],diverterSpeed:.5,diverterStroke:1,diverterAcceleration:1,diverterDeceleration:1}});
test('방향은 한 축의 양방향만 선택하고 초기화 후 축 변경 가능',()=>{assert.deepEqual(toggleDiverterDirection(['up'],'left'),['up']);assert.deepEqual(toggleDiverterDirection(['up'],'down'),['up','down']);assert.deepEqual(toggleDiverterDirection(['up'],'up'),[]);assert.deepEqual(toggleDiverterDirection([],'left'),['left']);});
test('직진과 선택한 방향만 허용하며 회전된 설비에서도 화면 기준 방향 사용',()=>{const cv=conveyor();assert.ok(diverterAllowsEdge(cv,{fromPort:'top'}));assert.ok(diverterAllowsEdge(cv,{fromPort:'right'}));assert.equal(diverterAllowsEdge(cv,{fromPort:'bottom'}),false);cv.rotation=90;assert.ok(diverterAllowsEdge(cv,{fromPort:'left'}));assert.equal(diverterAllowsEdge(cv,{fromPort:'top'}),false);});
test('프로파일 거리·속도·가감속을 반영하고 정속구간 및 짧은 거리 삼각형 지원',()=>{const cv=conveyor(),profile=diverterProfile(cv);assert.equal(profile.total,2.5);assert.ok(profile.t2>0);cv.parameters.diverterStroke=.01;assert.equal(diverterProfile(cv).t2,0);cv.parameters.diverterSpeed=2;assert.ok(diverterProfile(cv).peakSpeed<2);});
test('차단 중 분기 진행률은 되돌아가지 않고 정지, 중복 호출도 시간 중복 없음',()=>{const cv=conveyor(),token={},edge={from:'cv',to:'out',fromPort:'top'};assert.equal(advanceDiverterTransfer(token,cv,edge,0,true),false);advanceDiverterTransfer(token,cv,edge,1,true);const progress=token.diverterTransfer.progress;advanceDiverterTransfer(token,cv,edge,1,true);assert.equal(token.diverterTransfer.progress,progress);advanceDiverterTransfer(token,cv,edge,2,false);advanceDiverterTransfer(token,cv,edge,9,false);assert.equal(token.diverterTransfer.progress,progress);advanceDiverterTransfer(token,cv,edge,10,true);assert.equal(advanceDiverterTransfer(token,cv,edge,11.5,true),true);});
test('엔진은 선택 방향으로만 분기하고 승인 후 프로파일 완료까지 소유권 유지',()=>{const cv=conveyor(),up={id:'up',type:'sink',x:0,y:-100},down={id:'down',type:'sink',x:0,y:100},edge={from:'cv',to:'up',fromPort:'top',toPort:'bottom'},layout={equipment:[cv,up,down],cadSchematic:{edges:[edge,{from:'cv',to:'down',fromPort:'bottom'}]}},engine=new CadFlowEngine(layout),token=engine.prepareToken({id:1,nodeId:'cv',edge,cargoOrientation:.3,readyAt:0});engine.state.cadTokens=[token];engine.canAcceptNode=()=>true;assert.equal(engine.equipmentCapacity(cv),1);assert.equal(engine.outgoing.get('cv').length,1);assert.equal(engine.tryDirectHandover(token),false);engine.state.t=1;assert.equal(engine.tryDirectHandover(token),false);assert.equal(token.nodeId,'cv');engine.state.t=2.5;assert.equal(engine.tryDirectHandover(token),true);assert.equal(token.nodeId,'up');assert.equal(token.cargoOrientation,.3);});
test('서로 다른 축 혼합과 음수 디버터 파라미터는 실행 검증 차단',()=>{const cv=conveyor();cv.parameters.diverterDirections=['up','left'];cv.parameters.diverterSpeed=-1;assert.equal(validateFlowGraph({equipment:[cv]}).valid,false);});
