import test from 'node:test';
import assert from 'node:assert/strict';
import { DeterministicReliability, KinematicMotion, MotionState, kinematicTravelDuration } from '../src/kinematics.js';
import { handoverProgress, handoverScale, handoverVisualSegments, intervalsOverlap, itemVisualLength, OccupancyManager, rigidHandoverVisualState, smoothedVelocityProgress } from '../src/occupancy.js';
import { conveyorCargoVisualPose, conveyorFlowSign, equipmentCargoVisualPose, equipmentClipBounds, handoverEndpointPose, LayoutRenderer, pendingTransferPose, scaleRatioItemVisualSize, stableCargoVisualMetrics } from '../src/renderer.js';

test('S-Curve는 jerk로 가속도 변화량을 제한하고 정지까지 FSM을 추적한다',()=>{const motion=new KinematicMotion({targetSpeed:2,acceleration:1,deceleration:1,jerk:2});motion.step(.1,{distance:5});assert.ok(Math.abs(motion.acceleration-.2)<1e-9);assert.equal(motion.state,MotionState.ACCELERATING);for(let i=0;i<1000&&motion.position<5;i++)motion.step(.01,{distance:5});assert.equal(motion.position,5);assert.equal(motion.velocity,0);assert.equal(motion.state,MotionState.STOPPED);});

test('운행 중 목표속도 변경은 위치 순간이동 없이 현재 v와 a에서 연속 재계산한다',()=>{const motion=new KinematicMotion({targetSpeed:2,acceleration:1,deceleration:1,jerk:2});for(let i=0;i<100;i++)motion.step(.01,{distance:20});const before=motion.snapshot();motion.updateConfig({targetSpeed:.5});const after=motion.step(.01,{distance:20});assert.ok(after.position>=before.position);assert.ok(after.position-before.position<.1);assert.ok(Math.abs(after.velocity-before.velocity)<.1);});

test('고정 dt 운동 결과는 프레임 묶음 방식과 무관하다',()=>{const a=new KinematicMotion({targetSpeed:1.5,acceleration:.8,deceleration:1,jerk:1.5}),b=new KinematicMotion({targetSpeed:1.5,acceleration:.8,deceleration:1,jerk:1.5});for(let i=0;i<500;i++)a.step(.02,{distance:100});for(let frame=0;frame<100;frame++)for(let i=0;i<5;i++)b.step(.02,{distance:100});assert.deepEqual(a.snapshot(),b.snapshot());assert.ok(kinematicTravelDuration(10,{targetSpeed:1,acceleration:.8,deceleration:1,jerk:1.5})>10);});

test('MTBF/MTTR 모델은 같은 seed와 dt에서 동일한 정지 이벤트를 만든다',()=>{const params={mtbf:2,mttr:.5,microStopInterval:3,microStopDuration:.1},a=new DeterministicReliability(42),b=new DeterministicReliability(42),statesA=[],statesB=[];for(let i=0;i<500;i++){statesA.push(a.step(.02,params).available);statesB.push(b.step(.02,params).available);}assert.deepEqual(statesA,statesB);assert.ok(statesA.includes(false));});

test('공통 설비 표시 크기에서 실제 길이 비율대로 물류 크기를 계산한다',()=>{assert.equal(itemVisualLength(200,1,10),20);assert.equal(itemVisualLength(200,1,2),100);assert.equal(scaleRatioItemVisualSize(200,1,2),100);});

test('점유 관리자는 물류 길이와 안전간격을 포함해 후속 진입을 인터락한다',()=>{const manager=new OccupancyManager();manager.reserve('a','cv',2,1,.2);assert.equal(manager.canOccupy('b','cv',2.9,1,.2),false);assert.equal(manager.canOccupy('b','cv',4,1,.2),true);manager.release('a','cv');assert.equal(manager.canOccupy('b','cv',2.9,1,.2),true);assert.equal(intervalsOverlap({start:0,end:1},{start:1,end:2}),false);});

test('핸드오버는 head 진입부터 tail 이탈까지 양 설비 표시 길이를 연속 분할한다',()=>{assert.equal(handoverProgress(.5,1,1),.5);assert.deepEqual(handoverVisualSegments(.25,100),{sourceLength:75,targetLength:25});assert.deepEqual(handoverVisualSegments(1,100),{sourceLength:0,targetLength:100});});
test('핸드오버 스케일은 점유 비율을 smoothstep 보간하고 하나의 강체 길이를 유지한다',()=>{assert.deepEqual(handoverScale(0,20,100),{sourceWeight:1,targetWeight:0,scale:20});assert.deepEqual(handoverScale(1,20,100),{sourceWeight:0,targetWeight:1,scale:100});const middle=rigidHandoverVisualState(.5,1,20,100,20,100);assert.equal(middle.visualLength,60);assert.equal(middle.sourceWeight,.5);assert.equal(middle.targetWeight,.5);});
test('화면 속도 보간 진행률은 양 끝을 보존하고 속도 차이를 연속적으로 누적한다',()=>{assert.equal(smoothedVelocityProgress(0,20,100),0);assert.equal(smoothedVelocityProgress(1,20,100),1);const early=smoothedVelocityProgress(.25,20,100),late=smoothedVelocityProgress(.75,20,100);assert.ok(early>0&&early<.25);assert.ok(late>.5&&late<1);});
test('핸드오버 종료 위치와 다음 컨베이어 진입 위치는 같은 물리 좌표 변환을 사용한다',()=>{const cargo={length:1,width:.8},target={x:100,y:50,rotation:0,parameters:{length:2}},entered=conveyorCargoVisualPose(target,cargo,cargo.length,200);assert.equal(entered.visualLength,100);assert.equal(entered.x,50);assert.equal(entered.y,50);const nextFrame=conveyorCargoVisualPose(target,cargo,cargo.length+.01,200);assert.ok(nextFrame.x>entered.x);assert.ok(nextFrame.x-entered.x<2);assert.equal(nextFrame.visualLength,entered.visualLength);});
test('컨베이어 물류는 선택한 흐름 방향대로 진입하고 배출된다',()=>{const cargo={length:1,width:.8},right={x:100,y:50,rotation:0,parameters:{length:5,flowDirection:'right'}},left={...right,parameters:{...right.parameters,flowDirection:'left'}},rightStart=conveyorCargoVisualPose(right,cargo,1,100),rightNext=conveyorCargoVisualPose(right,cargo,2,100),leftStart=conveyorCargoVisualPose(left,cargo,1,100),leftNext=conveyorCargoVisualPose(left,cargo,2,100);assert.equal(conveyorFlowSign(right),1);assert.equal(conveyorFlowSign(left),-1);assert.ok(rightNext.x>rightStart.x);assert.ok(leftNext.x<leftStart.x);});
test('컨베이어 진입과 배출 경계에서도 물류가 완전히 사라지는 프레임을 만들지 않는다',()=>{const cargo={length:1.2,width:.8},item={x:100,y:50,rotation:0,parameters:{length:5}},metrics={visualLength:12,visualWidth:8},entry=conveyorCargoVisualPose(item,cargo,0,78,metrics),exit=conveyorCargoVisualPose(item,cargo,6.2,78,metrics),left=item.x-39,right=item.x+39;assert.ok(entry.x+metrics.visualLength/2>left);assert.ok(exit.x-metrics.visualLength/2<right);assert.equal(Math.round((entry.x+metrics.visualLength/2-left)*10)/10,2);assert.equal(Math.round((right-(exit.x-metrics.visualLength/2))*10)/10,2);});
test('포킹장치 물류는 받기·대기·보내기 단계에서 계속 표시된다',()=>{const input={id:'a',type:'conveyor',x:0,y:0},fork={id:'fork',type:'forkingDevice',x:100,y:0,parameters:{strokeDistance:1,receiveSpeed:1,holdTime:2,transferSpeed:1}},output={id:'b',type:'conveyor',x:200,y:0},edges=[{from:'a',to:'fork',fromPort:'right',toPort:'left'},{from:'fork',to:'b',fromPort:'right',toPort:'left'}],layout={equipment:[input,fork,output],cadSchematic:{edges}},token={nodeId:'fork',nodeEnteredAt:0,operationDuration:4,handover:{edge:edges[0]}},receiving=equipmentCargoVisualPose(layout,fork,{t:.5},token,12),waiting=equipmentCargoVisualPose(layout,fork,{t:2},token,12),sending=equipmentCargoVisualPose(layout,fork,{t:3.5},token,12);for(const pose of [receiving,waiting,sending])assert.ok(Number.isFinite(pose.x)&&Number.isFinite(pose.y));assert.ok(receiving.x<waiting.x);assert.equal(waiting.x,fork.x);assert.ok(sending.x>waiting.x);});
test('서로 다른 실제 길이의 설비를 지나도 물류 강체 표시 크기는 변하지 않는다',()=>{const cargo={length:1.2,width:.8},layout={equipment:[{type:'conveyor',source:{origin:'dxf'},parameters:{length:2}},{type:'conveyor',source:{origin:'dxf'},parameters:{length:10}}]},metrics=stableCargoVisualMetrics(layout,cargo,78),short=conveyorCargoVisualPose(layout.equipment[0],cargo,1,78,metrics),long=conveyorCargoVisualPose(layout.equipment[1],cargo,1,78,metrics);assert.equal(short.visualLength,long.visualLength);assert.equal(short.visualWidth,long.visualWidth);assert.ok(short.visualLength>0&&short.visualLength<78);});
test('컨베이어에서 포크로 진입할 때도 직접 핸드오버 표시가 유지된다',()=>{const source={id:'cv',type:'conveyor',parameters:{length:5}},fork={id:'fork',type:'forkingDevice',parameters:{}},edge={from:'cv',to:'fork'},layout={cadSchematic:{edges:[edge]}},nodes=new Map([['cv',source],['fork',fork]]),token={nodeId:'cv',edge:null,motion:{},motionState:{position:5.6}},descriptor=LayoutRenderer.prototype.handoverDescriptor.call({layout},token,{t:1},nodes,{length:1.2});assert.equal(descriptor.source,source);assert.equal(descriptor.target,fork);assert.equal(descriptor.edge,edge);assert.ok(descriptor.raw>0&&descriptor.raw<1);});
test('포크에 도착한 물류는 이전 핸드오버에 가려지지 않고 처리 대기 중 포크 위에 표시된다',()=>{const source={id:'cv',type:'conveyor',parameters:{length:5}},fork={id:'fork',type:'forkingDevice',parameters:{forkTime:4}},edge={from:'cv',to:'fork'},layout={cadSchematic:{edges:[edge]}},nodes=new Map([['cv',source],['fork',fork]]),token={nodeId:'fork',edge:null,motion:null,readyAt:5,handover:{sourceId:'cv',targetId:'fork',edge,startedAt:0,duration:2}},descriptor=LayoutRenderer.prototype.handoverDescriptor.call({layout},token,{t:1},nodes,{length:1.2});assert.equal(descriptor,null);});
test('다음 설비가 막혀을 때 물류는 연결선으로 사라지지 않고 현재 설비에 대기한다',()=>{const fork={id:'fork',type:'forkingDevice',parameters:{forkTime:4}},target={id:'cv',type:'conveyor',parameters:{length:5}},edge={from:'fork',to:'cv'},layout={cadSchematic:{edges:[edge]}},nodes=new Map([['fork',fork],['cv',target]]),token={nodeId:'fork',edge,progress:1,motion:null,handover:{sourceId:'fork',targetId:'cv',edge,startedAt:1,duration:2}},descriptor=LayoutRenderer.prototype.handoverDescriptor.call({layout},token,{t:2},nodes,{length:1.2});assert.equal(descriptor,null);});
test('컨베이어·포크·AGV 등의 인계 대기 물류는 설비 출력단 안쪽에 유지된다',()=>{for(const type of ['conveyor','forkingDevice','agv','amr','turntable']){const source={id:type,type,x:100,y:100,rotation:0},target={id:'target',type:'conveyor',x:300,y:100,rotation:0},pose=pendingTransferPose(source,target,{fromPort:'right'},20);const bounds=equipmentClipBounds(source),right=source.x+bounds.width/2;assert.equal(pose.x+10,right);assert.equal(pose.y,source.y);}});
test('물류는 핸드오버 오버레이와 중복 분리하지 않고 현재 소유 설비에서 항상 한 번 표시된다',()=>{const source={id:'a',type:'forkingDevice',x:0,y:0},target={id:'b',type:'conveyor',x:100,y:0},edge={from:'a',to:'b',fromPort:'right',toPort:'left'},pose=pendingTransferPose(source,target,edge,20);assert.equal(pose.x+10,equipmentClipBounds(source).width/2);});
test('핸드오버 물류는 강체 이동 좌표를 유지하며 설비 경계를 통과한다',()=>{const a={x:100,y:100,rotation:0,type:'conveyor'},b={x:300,y:200,rotation:0,type:'conveyor'},sourceStart=handoverEndpointPose(a,'right',20,false,b,0),sourceEnd=handoverEndpointPose(a,'right',20,false,b,1),targetStart=handoverEndpointPose(b,'top',20,true,a,0),targetEnd=handoverEndpointPose(b,'top',20,true,a,1);assert.deepEqual(equipmentClipBounds(a),{width:78,height:28});assert.deepEqual({x:sourceStart.x,y:sourceStart.y},{x:129,y:100});assert.deepEqual({x:sourceEnd.x,y:sourceEnd.y},{x:149,y:100});assert.deepEqual({x:targetStart.x,y:targetStart.y},{x:300,y:176});assert.deepEqual({x:targetEnd.x,y:targetEnd.y},{x:300,y:196});assert.equal(sourceStart.angle,0);assert.ok(Math.abs(targetStart.angle-Math.PI/2)<1e-9);});
