import { cloneLayout, defaultLayout, validateLayout } from './layout.js';
import { CadFlowEngine, defaultParams, SimulationEngine, simulationEventText, validateParams } from './engine.js';
import { cargoColor, flowColor, LayoutRenderer } from './renderer.js';
import { LayoutEditor, refreshEquipmentConnections } from './editor.js';
import { analyzeCadFile, ensureDynamicParameters, parameterFieldsFor } from './cad.js';
import { buildSimulationReport } from './report.js';
import { closestPortPair, connectionKind } from './route.js';
import { drawAsrsScene } from './asrs-monitor.js';
import { motionConfigFor, motionProfileSummary, recommendedMotionDynamics } from './kinematics.js';

const $ = id => document.getElementById(id);
const emptyLayout={schemaVersion:defaultLayout.schemaVersion,id:'empty-layout',name:'파일을 열어주세요',cargoSpec:{length:1200,width:800,weight:100,unit:'mm'},canvas:{width:1200,height:650,grid:20},equipment:[],connections:[],displayMode:'cad',cadViewMode:'schematic',cadSchematic:{lanes:[],inboundBranches:[],edges:[]}};
let layout = cloneLayout(emptyLayout), engine = new SimulationEngine(cloneLayout(defaultLayout), defaultParams);
let renderer = new LayoutRenderer($('layoutCanvas'), layout), running = false, frame = null, last = 0;
let selectedEquipment = null;
let selectedConnectionIndex = null;
let pendingCadCandidates = [];
let flowLegendSignature='';
const editor = new LayoutEditor($('layoutCanvas'), renderer, () => layout, editorChanged, selectEquipment, connectEquipment, editorModeChanged, selectConnection);
const cadParameterSection=document.createElement('section');cadParameterSection.id='cadEquipmentParameters';cadParameterSection.className='cad-parameter-section';cadParameterSection.hidden=true;
$('dynamicEquipmentControls').append(cadParameterSection);
const emptyProjectState=document.createElement('div');emptyProjectState.id='emptyProjectState';emptyProjectState.className='empty-project-state';emptyProjectState.innerHTML='<strong>새 레이아웃을 시작하세요</strong><span>DXF 파일 또는 이미 저장된 JSON 파일을 열어주세요.</span>';$('layoutCanvas').closest('.canvas-scroll').before(emptyProjectState);
const newLayoutButton=document.createElement('button');newLayoutButton.id='newLayoutProject';newLayoutButton.textContent='새 레이아웃 구성';$('cadFile').closest('.layout-actions').prepend(newLayoutButton);
const projectStatus=document.createElement('small');projectStatus.id='projectStatus';projectStatus.className='project-status';$('layoutName').after(projectStatus);
const rackMonitor=document.createElement('section');rackMonitor.id='rackMonitor';rackMonitor.className='rack-monitor';rackMonitor.hidden=true;$('rackMonitorSlot').append(rackMonitor);
const lineUphPanel=document.createElement('section');lineUphPanel.id='lineUphPanel';lineUphPanel.className='line-uph-panel';lineUphPanel.hidden=true;$('rackMonitorSlot').prepend(lineUphPanel);
const visualDialog=document.createElement('dialog');visualDialog.id='visualDialog';visualDialog.className='visual-dialog';visualDialog.innerHTML='<div class="visual-dialog-head"><h2></h2><button type="button" data-close-visual>닫기</button></div><div class="visual-dialog-body"></div>';document.body.append(visualDialog);
for(const [type,label] of [['source','입고 시작'],['dock','트럭/도크'],['handoffPoint','H/P'],['sorter','소터'],['lift','리프트'],['asrs','AS/RS'],['sink','출고 완료']]){if(document.querySelector(`[data-add="${type}"]`))continue;const button=document.createElement('button');button.dataset.add=type;button.textContent=label;$('connectEquipment').before(button);}

const inputKeys = ['injectA','injectB','injectC','conv2Speed','conv1Speed','pickTime','placeTime','station15Time','station16Time','forklift17Time','forklift211Time','simDuration'];
function readParams() {
  return { useA:$('useA').checked, useB:$('useB').checked, ...Object.fromEntries(inputKeys.map(key=>[key,Number($(key).value)])) };
}
function writeParams(params={}){const values={...defaultParams,...params};for(const key of inputKeys)$(key).value=values[key];$('useA').checked=Boolean(values.useA);$('useB').checked=Boolean(values.useB);}
function updateProjectStatus(){projectStatus.textContent=`현재 프로젝트 · ${layout.id==='empty-layout'?'없음':layout.name}`;}
function setProjectEmpty(value){document.body.classList.toggle('project-empty',value);emptyProjectState.hidden=!value;$('layoutName').textContent=value?'파일을 열어주세요':layout.name;updateProjectStatus();}
function ensureCargoSpecMm(target=layout){const source=target.cargoSpec||{},legacyMeters=source.unit!=='mm'&&Number(source.length||0)<=20&&Number(source.width||0)<=20,scale=legacyMeters?1000:1;target.cargoSpec={length:Math.max(1,Number(source.length||(legacyMeters?1.2:1200))*scale),width:Math.max(1,Number(source.width||(legacyMeters ? .8 : 800))*scale),weight:Math.max(.01,Number(source.weight||100)),unit:'mm'};return target.cargoSpec;}
function updateFlowLegend(){const names=Object.keys(engine.state?.asrs?.zones||{}),tokens=engine.state?.cadTokens||[],pairs=new Map();for(const token of tokens){const line=token.flowKey,cargo=token.cargoType||token.originFlowKey||line;if(line&&cargo&&cargo!==line)pairs.set(`${cargo}|${line}`,token);}const entries=names.map((name,index)=>({label:name,line:name,index,cargo:null}));for(const token of pairs.values())entries.push({label:`${token.cargoType||token.originFlowKey} → ${token.flowKey}`,line:token.flowKey,index:token.flowIndex,cargo:token.cargoType||token.originFlowKey});const signature=entries.map(item=>`${item.cargo||''}>${item.line}`).join('|');if(signature===flowLegendSignature)return;flowLegendSignature=signature;const legend=$('flowLegend');legend.replaceChildren(...entries.map(item=>{const entry=document.createElement('span'),swatch=document.createElement('i'),label=document.createTextNode(item.label);swatch.style.background=item.cargo?cargoColor(item.cargo,item.index):flowColor(item.line,item.index);swatch.style.color=flowColor(item.line,item.index);swatch.style.border=`1px solid ${flowColor(item.line,item.index)}`;entry.append(swatch,label);return entry;}));}
function syncFlowView(){const select=$('flowView'),current=select.value||'all',names=Object.keys(engine.state?.asrs?.zones||{});select.replaceChildren(new Option('전체 물류','all'),...names.map(name=>new Option(`${name}만`,name)));select.value=names.includes(current)?current:'all';renderer.setFlowFilter(select.value);updateFlowLegend();}
function resetEngine() {
  const params=readParams(), check=validateParams(params);
  $('validation').textContent=check.errors.join(' ');
  if(!check.valid) return false;
  engine=layout.displayMode==='cad'?new CadFlowEngine(layout,params):new SimulationEngine(layout,params);syncFlowView();renderer.draw(engine.state); updateDashboard(); renderEvents(); return true;
}
function editorChanged(rebuild) {
  if (rebuild) {renderer.setLayout(layout);resetEngine();return;}
  renderer.draw(engine.state);
}
function editorModeChanged(mode){$('connectEquipment').classList.toggle('active',mode.connecting);if(mode.selectionCount>1){$('connectionHint').hidden=false;$('connectionHint').textContent=`${mode.selectionCount}개 설비 선택됨 · 선택된 설비를 드래그하면 함께 이동합니다.`;}else if(mode.insertion){$('connectionHint').hidden=false;$('connectionHint').textContent=`자동 삽입 완료: 기존 연결선을 제거하고 ${mode.item.name} 양옆으로 다시 연결했습니다.`;}else if(mode.placement){$('connectionHint').hidden=false;$('connectionHint').textContent=`${mode.placement.toUpperCase()} 배치 위치를 클릭하세요. 기존 연결선 위에 놓으면 선 사이에 자동 삽입됩니다.`;}else if(mode.connecting){const source=layout.equipment.find(item=>item.id===mode.sourceId);$('connectionHint').hidden=false;$('connectionHint').textContent=source?`${source.name}의 ${mode.fromPort} 연결점에서 원하는 도착 연결점까지 드래그하세요.`:'시작 설비의 연결점을 누른 채 도착 설비 연결점까지 드래그하세요. 초록점은 출력, 하늘색점은 입력입니다.';}else if(!$('connectionHint').textContent.startsWith('연결 완료')&&!$('connectionHint').textContent.startsWith('자동 삽입 완료'))$('connectionHint').hidden=true;}
function connectEquipment(fromId,toId,fromPort,toPort){if(fromId===toId)return false;layout.cadSchematic??={lanes:[],inboundBranches:[],edges:[]};layout.cadSchematic.edges??=[];if(layout.cadSchematic.edges.some(edge=>edge.from===fromId&&edge.to===toId&&edge.fromPort===fromPort&&edge.toPort===toPort))return false;const from=layout.equipment.find(item=>item.id===fromId),to=layout.equipment.find(item=>item.id===toId);if(!from||!to)return false;const ports=fromPort&&toPort?{fromPort,toPort}:closestPortPair(from,to),kind=connectionKind(from,to);layout.cadSchematic.edges.push({from:fromId,to:toId,kind,fromPort:ports.fromPort,toPort:ports.toPort,manual:true});$('connectionHint').hidden=false;$('connectionHint').textContent=`연결 완료: ${from.name} ${ports.fromPort} → ${to.name} ${ports.toPort}`;renderer.setLayout(layout);resetEngine();return true;}
function selectEquipment(item) {
  const changed=selectedEquipment?.id!==item?.id;
  selectedEquipment=item;
  for(const id of ['propName','propX','propY','propRotation','rotateLeft','rotateRight']) $(id).disabled=!item;
  $('deleteEquipment').disabled=!item;
  $('propName').value=item?.name||'';$('propX').value=item?.x??'';$('propY').value=item?.y??'';$('propRotation').value=item?.rotation??0;
  if(changed&&layout.displayMode==='cad')renderCadEquipmentParameters(item?.source?.origin==='dxf'?item.id:null);
}
function selectConnection(edge,index,context){selectedConnectionIndex=edge&&Number.isInteger(index)?index:null;$('deleteConnection').disabled=selectedConnectionIndex===null;const menu=$('edgeContextMenu');if(context&&edge){menu.hidden=false;menu.style.left=`${Math.min(context.x,window.innerWidth-130)}px`;menu.style.top=`${Math.min(context.y,window.innerHeight-50)}px`;}else menu.hidden=true;if(edge){const from=layout.equipment.find(item=>item.id===edge.from),to=layout.equipment.find(item=>item.id===edge.to);$('connectionHint').hidden=false;$('connectionHint').textContent=`연결선 선택: ${from?.name||edge.from} → ${to?.name||edge.to}`;}}
function deleteSelectedConnection(){if(selectedConnectionIndex===null)return;if(editor.removeEdge(selectedConnectionIndex)){selectedConnectionIndex=null;$('deleteConnection').disabled=true;$('edgeContextMenu').hidden=true;$('connectionHint').hidden=false;$('connectionHint').textContent='연결선을 삭제했습니다.';resetEngine();}}
function updateDashboard() {
  const k=engine.getKpis(), names={robot:'로봇',station15:'1-5',station16:'1-6',forklift17:'1-7 지게차',forklift211:'2-11 지게차'};
  $('simTime').textContent=format(engine.state.t); $('throughput').textContent=k.throughput.toFixed(1)+'/h';
  $('throughputLabel').textContent=k.mode==='cad'?'UPH':'1-7 처리량';$('secondaryKpiLabel').textContent=k.mode==='cad'?'평균 CT':'로봇 가동률';$('robotUtil').textContent=k.mode==='cad'?k.cycleTime.toFixed(1)+'초':(k.utilization.robot*100).toFixed(1)+'%'; $('wip').textContent=k.wip;
  $('bottleneck').textContent=k.bottleneck?`${names[k.bottleneck[0]]} ${(k.bottleneck[1]*100).toFixed(0)}%`:'-';
  $('moved').textContent=k.movedItems; $('completed').textContent=engine.state.completedProducts.length;
  updateFlowLegend();
  renderEvents();
  renderSimulationReport();
  renderLineThroughput(k);
  renderRackMonitor();
}
function renderLineThroughput(kpis){const rows=kpis.lineThroughput||[];lineUphPanel.hidden=!rows.length;if(!rows.length)return;lineUphPanel.replaceChildren();const title=document.createElement('h2');title.textContent='라인별 UPH';lineUphPanel.append(title);const table=document.createElement('table'),head=document.createElement('thead'),body=document.createElement('tbody'),header=document.createElement('tr');for(const label of ['라인','생성','AS/RS 입고','AS/RS 출고']){const cell=document.createElement('th');cell.textContent=label;header.append(cell);}head.append(header);for(const row of rows){const tr=document.createElement('tr');for(const value of [row.name,row.generatedUph,row.asrsInboundUph,row.asrsOutboundUph]){const cell=document.createElement('td');cell.textContent=typeof value==='number'?value.toFixed(1):value;tr.append(cell);}body.append(tr);}table.append(head,body);lineUphPanel.append(table);}
function renderRackMonitor(){
  const asrs=engine.state?.asrs,equipment=layout.equipment.find(item=>item.id===asrs?.equipmentId);
  if(!asrs?.equipmentId||!equipment){rackMonitor.hidden=true;return;}
  rackMonitor.hidden=false;
  rackMonitor.innerHTML=`<div class="rack-monitor-head"><h2>AS/RS 3D LIVE</h2><span><strong>${asrs.inventory}/${asrs.capacity}</strong><button type="button" data-expand-asrs>확대</button></span></div><div class="rack-flow-key"><span class="inbound">입고중</span><span class="outbound">배출중</span><span>대기중</span></div><canvas class="asrs-scene" aria-label="AS/RS 스태커 크레인 3D 실시간 동작"></canvas>`;
  drawAsrsScene(rackMonitor.querySelector('.asrs-scene'),equipment,engine.state,flowColor,cargoColor);
  if(visualDialog.open&&visualDialog.dataset.visualType==='asrs'){const expanded=visualDialog.querySelector('.asrs-scene-expanded');if(expanded)drawAsrsScene(expanded,equipment,engine.state,flowColor,cargoColor);}
}
function openVisualDialog(type,title){if(visualDialog.open)visualDialog.close();visualDialog.dataset.visualType=type;visualDialog.querySelector('h2').textContent=title;const body=visualDialog.querySelector('.visual-dialog-body');body.replaceChildren();if(type==='asrs'){const canvas=document.createElement('canvas');canvas.className='asrs-scene asrs-scene-expanded';body.append(canvas);const asrs=engine.state?.asrs,equipment=layout.equipment.find(item=>item.id===asrs?.equipmentId);if(equipment)drawAsrsScene(canvas,equipment,engine.state,flowColor,cargoColor);}visualDialog.showModal();}
rackMonitor.addEventListener('click',event=>{if(event.target.closest('[data-expand-asrs]'))openVisualDialog('asrs','AS/RS 3D LIVE 확대');});
cadParameterSection.addEventListener('click',event=>{const button=event.target.closest('[data-expand-motion]');if(!button)return;const card=cadParameterSection.querySelector(`[data-parameter-card="${CSS.escape(button.dataset.expandMotion)}"]`),profiles=[...card?.querySelectorAll('.motion-profile-card')||[]].map(node=>node.cloneNode(true));openVisualDialog('motion',`${layout.equipment.find(item=>item.id===button.dataset.expandMotion)?.name||'설비'} · 예상 구동 속도 프로파일`);const body=visualDialog.querySelector('.visual-dialog-body');for(const profile of profiles){profile.hidden=false;profile.querySelectorAll('.visual-expand-button').forEach(entry=>entry.remove());body.append(profile);}});
visualDialog.addEventListener('click',event=>{if(event.target.closest('[data-close-visual]')||event.target===visualDialog)visualDialog.close();});
function renderSimulationReport(){const panel=$('simulationReport');if(layout.displayMode!=='cad'||!layout.equipment.some(item=>item.source?.origin==='dxf')){panel.hidden=true;return;}panel.hidden=false;const report=buildSimulationReport(layout,engine),asrs=report.kpis.asrs;$('reportContent').innerHTML=`<div class="report-grid"><section class="report-block"><h3>1. 🛠️ Layout Corrections</h3><ul>${report.corrections.map(item=>`<li>[${item.kind}] ${item.detail} · ${item.status}</li>`).join('')}</ul></section><section class="report-block"><h3>2. 📐 Corrected Flow & Topology</h3><ul>${report.topology.map(item=>`<li>${item}</li>`).join('')}</ul></section><section class="report-block wide"><h3>3. ⏱️ 공정별 CT 및 병목</h3><div class="table-wrap"><table><thead><tr><th>공정명</th><th>거리(m)</th><th>이동(sec)</th><th>작업(sec)</th><th>공정 CT</th><th>병목</th></tr></thead><tbody>${report.rows.map(row=>`<tr><td>${row.process}</td><td>${row.distance.toFixed(1)}</td><td>${row.move.toFixed(1)}</td><td>${row.work.toFixed(1)}</td><td>${row.ct.toFixed(1)}</td><td>${row.bottleneck?'병목':'-'}</td></tr>`).join('')}</tbody></table></div></section><section class="report-block wide"><h3>4. 📊 UPH 및 생산성 예측</h3><div class="report-metrics"><div>Target UPH<strong>${report.targetUph.toFixed(1)}</strong></div><div>Realizable UPH<strong>${report.realizableUph.toFixed(1)}</strong></div><div>8시간 물동량<strong>${Math.floor(report.eightHours)}</strong></div><div>12시간 물동량<strong>${Math.floor(report.twelveHours)}</strong></div>${asrs?`<div>AS/RS 재고<strong>${asrs.inventory}/${asrs.capacity}</strong></div><div>AS/RS 가동률<strong>${(report.kpis.utilization.asrs*100).toFixed(1)}%</strong></div>`:''}</div></section></div>`;}
function loop(now) {
  if(!running) return; if(!last) last=now;
  const simDt=Math.min((now-last)/1000*Number($('playback').value),2); last=now;
  const steps=Math.max(1,Math.ceil(simDt/.05)); for(let i=0;i<steps;i++) engine.step(simDt/steps);
  renderer.draw(engine.state); updateDashboard();
  if(engine.state.t>=engine.params.simDuration){running=false;$('runBtn').textContent='완료';renderEvents();return;}
  frame=requestAnimationFrame(loop);
}
function toggleRun() {
  if(engine.state.t===0&&!resetEngine()) return;
  running=!running; $('runBtn').textContent=running?'일시정지':'재개'; last=0;
  if(running) frame=requestAnimationFrame(loop); else {cancelAnimationFrame(frame);renderEvents();}
}
function renderEvents() {
  const rows=engine.state.events.slice(-12).reverse();
  $('eventRows').innerHTML=rows.length?rows.map(e=>`<tr><td>${format(e.t)}</td><td>${eventLabel(e.type)}</td><td>${e.equipmentId||e.kind||''}</td><td>#${e.trayId||e.productId||'-'}</td></tr>`).join(''):'<tr><td colspan="4">아직 이벤트가 없습니다.</td></tr>';
}
function eventLabel(type){return ({'source-injected':'소스 투입','product-injected':'C 투입','robot-pick-start':'PICK 시작','robot-place-complete':'PLACE 완료','equipment-start':'설비 작업 시작','equipment-complete':'설비 작업 완료','asrs-putaway':'AS/RS 적치','asrs-retrieval':'AS/RS 반출','cargo-overload':'허용하중 초과','cargo-wait-started':'물류 대기 시작','cargo-wait-ended':'물류 대기 해제'})[type]||type;}
function format(s){const m=Math.floor(s/60),sec=Math.floor(s%60);return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);}

$('runBtn').addEventListener('click',toggleRun);
$('flowView').addEventListener('change',()=>{renderer.setFlowFilter($('flowView').value);renderer.draw(engine.state);});
$('resetBtn').addEventListener('click',()=>{running=false;cancelAnimationFrame(frame);resetEngine();$('runBtn').textContent='시뮬레이션 시작';});
$('exportLayout').addEventListener('click',()=>download('conveyor-layout.json',JSON.stringify({...layout,simulationParams:readParams()},null,2)));
$('exportEvents').addEventListener('click',()=>{const safeName=(layout.name||'simulation').replace(/[\\/:*?"<>|]+/g,'_');download(`${safeName}-events.txt`,simulationEventText(engine.state,layout),'text/plain;charset=utf-8');});
$('exportDiagnostics').addEventListener('click',()=>{const safeName=(layout.name||'simulation').replace(/[\\/:*?"<>|]+/g,'_'),text=engine instanceof CadFlowEngine?engine.flowDiagnosticText():'CAD 시뮬레이션에서 사용할 수 있습니다.';download(`${safeName}-stall-diagnostic.txt`,text,'text/plain;charset=utf-8');});
$('editorToggle').addEventListener('click',()=>{const active=$('editorTools').hidden;$('editorTools').hidden=!active;editor.setEnabled(active);$('editorToggle').textContent=active?'편집 종료':'편집 모드';});
$('viewFit').addEventListener('click',()=>editor.fitView());
$('cadViewToggle').addEventListener('click',()=>{if(layout.displayMode!=='cad')return;const order=['hybrid','schematic','raw'],labels={hybrid:'보기: 혼합',schematic:'보기: 약식',raw:'보기: CAD'},next=order[(order.indexOf(layout.cadViewMode)+1)%order.length];layout.cadViewMode=next;for(const item of layout.equipment.filter(entry=>entry.source?.origin==='dxf')){const position=next==='schematic'?item.normalizedPosition:item.originalPosition;if(position){item.x=position.x;item.y=position.y;}}$('cadViewToggle').textContent=labels[next];renderer.setLayout(layout);editor.resetView();renderer.draw(engine.state);});
$('drawingFile').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;const dataUrl=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file);});layout.background={name:file.name,dataUrl};await renderer.setBackground(dataUrl);renderer.draw(engine.state);event.target.value='';});
$('cadFile').addEventListener('change',async event=>{
  const file=event.target.files[0];if(!file)return;const panel=$('cadStatus');panel.hidden=false;$('cadStatusTitle').textContent='DXF 로컬 분석 중';$('cadStatusText').textContent=`${file.name}의 좌표, 레이어, 블록과 문자를 브라우저에서 읽고 있습니다.`;$('cadCandidates').innerHTML='';
  try{
    const result=await analyzeCadFile(file),candidates=result.candidates.filter(item=>item.type!=='unknown');
    layout.cadSource={fileName:file.name,analyzedAt:new Date().toISOString(),units:result.document.units||'unknown',importId:candidates[0]?.source?.importId};setProjectEmpty(false);
    layout.dxfGeometry=result.document.canvasGeometry;layout.cadSchematic=result.schematic;layout.cadViewMode='schematic';layout.canvas.height=Math.max(result.document.canvasHeight,650);layout.displayMode='cad';layout.equipment=layout.equipment.filter(item=>item.source?.origin!=='dxf');$('cadViewToggle').textContent='보기: 약식';
    renderer.setLayout(layout);renderer.draw(engine.state);pendingCadCandidates=candidates;$('cadStatusTitle').textContent='DXF 분석 완료';$('cadStatusText').textContent=`원본 라인 ${layout.dxfGeometry.length}개와 설비 후보 ${candidates.length}개를 찾았습니다. 라인워크 위에 승인 설비가 배치됩니다.`;renderCadCandidates();renderCadEquipmentParameters();
  }catch(error){$('cadStatusTitle').textContent='DXF 분석 실패';$('cadStatusText').textContent=error.message;}
  finally{event.target.value='';}
});
function renderCadCandidates(){
  const host=$('cadCandidates');
  host.innerHTML=pendingCadCandidates.length?`<div class="candidate-actions"><button data-cad-action="approve-all">모두 승인</button><button data-cad-action="discard-all">모두 제외</button></div>`+pendingCadCandidates.map(item=>`<div class="candidate-card"><span>${item.name}</span><small>${item.type} · 신뢰도 ${Math.round(item.confidence*100)}%</small><button data-cad-action="approve" data-id="${item.id}">승인</button><button data-cad-action="discard" data-id="${item.id}">제외</button></div>`).join(''):'<span>검수할 후보가 없습니다.</span>';
}
function detectedFlowNames(){return [...new Set([...(layout.cadSchematic?.lanes||[]).map(line=>line.name),...(layout.cadSchematic?.inboundBranches||[]).map(line=>line.name),...Object.keys(engine.state?.asrs?.zones||{})].filter(Boolean))];}
function appendForkParameterControls(items){const flowNames=detectedFlowNames();for(const item of items.filter(entry=>entry.type==='forkingDevice')){item.parameters??={};const card=cadParameterSection.querySelector(`[data-parameter-card="${CSS.escape(item.id)}"]`),ratioInput=card?.querySelector('[data-parameter="output1Ratio"]'),ratioLabel=ratioInput?.closest('label');if(!card||!ratioLabel)continue;const enabled=item.parameters.distributionEnabled!==false,configured=Array.isArray(item.parameters.distributionFlowKeys)?item.parameters.distributionFlowKeys:[],selected=configured.length?configured:flowNames,role=document.createElement('label');role.className='fork-role-toggle';const roleText=document.createElement('span');roleText.textContent='분배 역할 사용';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=enabled;checkbox.dataset.forkEnabled='';checkbox.dataset.forkId=item.id;role.append(roleText,checkbox);ratioLabel.before(role);const selector=document.createElement('div');selector.className='fork-flow-selector';const title=document.createElement('strong');title.textContent='분배할 출발 라인 화살표';const hint=document.createElement('small');hint.textContent=enabled?'선택한 라인에서 온 물류만 직행/교차 순차 분배합니다.':'분배 역할이 꺼져 있어 모든 물류가 주 흐름으로 직행합니다.';const buttons=document.createElement('div');buttons.className='fork-flow-buttons';for(const name of flowNames){const button=document.createElement('button');button.type='button';button.textContent=name;button.dataset.forkFlow=name;button.dataset.forkId=item.id;button.classList.toggle('selected',selected.includes(name));button.disabled=!enabled;buttons.append(button);}selector.append(title,buttons,hint);ratioLabel.after(selector);}}
function appendConveyorHandoverControls(items){for(const item of items.filter(entry=>entry.type==='conveyor')){item.parameters??={};item.parameters.continuousHandover??=1;item.parameters.handoverDelay??=0;const card=cadParameterSection.querySelector(`[data-parameter-card="${CSS.escape(item.id)}"]`);if(!card)continue;const continuous=document.createElement('label'),continuousText=document.createElement('span'),checkbox=document.createElement('input');continuousText.textContent='다음 설비로 연속 이동';checkbox.type='checkbox';checkbox.checked=item.parameters.continuousHandover!==0;checkbox.dataset.parameterCheckbox='continuousHandover';checkbox.dataset.parameter='continuousHandover';checkbox.dataset.checkboxEquipmentId=item.id;continuous.append(continuousText,checkbox);const delay=document.createElement('label');delay.innerHTML=`비연속 인계 대기시간(초)<span><input type="number" min="0" step="0.1" data-equipment-id="${item.id}" data-parameter="handoverDelay" value="${Math.max(0,Number(item.parameters.handoverDelay)||0)}"></span>`;card.append(continuous,delay);}}
function appendAsrsBatchControls(items){for(const item of items.filter(entry=>['asrs','stackerCrane'].includes(entry.type))){item.parameters??={};item.parameters.batchReleaseEnabled??=0;item.parameters.releaseBatchSize??=16;const card=cadParameterSection.querySelector(`[data-parameter-card="${CSS.escape(item.id)}"]`);if(!card)continue;const group=document.createElement('div');group.className='fork-flow-selector';const title=document.createElement('strong');title.textContent='셀 재고 묶음 배출';const toggle=document.createElement('label'),text=document.createElement('span'),checkbox=document.createElement('input');text.textContent='설정 수량 적재 후 출고 시작';checkbox.type='checkbox';checkbox.checked=item.parameters.batchReleaseEnabled!==0;checkbox.dataset.parameterCheckbox='batchReleaseEnabled';checkbox.dataset.parameter='batchReleaseEnabled';checkbox.dataset.checkboxEquipmentId=item.id;toggle.append(text,checkbox);const amount=document.createElement('label');amount.innerHTML=`배출 시작 적재 수량<span><input type="number" min="1" step="1" data-equipment-id="${item.id}" data-parameter="releaseBatchSize" value="${Math.max(1,Math.round(Number(item.parameters.releaseBatchSize)||16))}"></span>`;const hint=document.createElement('small');hint.textContent='품목별 재고가 설정 수량에 도달하면 그 수량만 순차 출고합니다.';group.append(title,toggle,amount,hint);card.append(group);}}
function appendSourceCargoControls(items){for(const item of items.filter(entry=>entry.type==='source'||(entry.type==='dock'&&entry.parameters?.dockRole==='inbound'))){item.parameters??={};const card=cadParameterSection.querySelector(`[data-parameter-card="${CSS.escape(item.id)}"]`);if(!card)continue;const branch=(layout.cadSchematic?.inboundBranches||[]).find(entry=>entry.nodeIds?.includes(item.id)),label=document.createElement('label'),text=document.createElement('span'),input=document.createElement('input'),hint=document.createElement('small');text.textContent='투입 물품 종류';input.type='text';input.value=item.parameters.cargoType||branch?.cargoType||branch?.name||item.name||'물류';input.dataset.sourceCargoType=item.id;input.placeholder='예: 트림 물류';hint.textContent='라인 소속과 별개입니다. 이 값의 색으로 물류 본체와 AS/RS 셀이 표시됩니다.';label.append(text,input);card.append(label,hint);}}
function equipmentProfileDistance(item){const p=item.parameters||{};if(['asrs','stackerCrane'].includes(item.type))return Math.max(.1,(Math.max(1,Number(p.columns)||1)-1)*Math.max(.1,Number(p.columnPitch)||1.5));if(item.type==='conveyor'||item.type==='sorter')return Math.max(.1,Number(p.length)||5);if(['agv','amr','shuttle'].includes(item.type))return Math.max(.1,Number(p.shuttleDistance)||5);if(item.type==='forklift')return Math.max(.1,Number(p.travelDistance)||5);if(item.type==='lift')return Math.max(.1,Number(p.liftHeight)||3);if(item.type==='forkingDevice')return Math.max(.1,Number(p.strokeDistance)||1.5);return 0;}
function storageMotionAxes(item){const p=item.parameters||{},horizontal=Math.max(.1,(Math.max(1,Number(p.columns)||1)-1)*Math.max(.1,Number(p.columnPitch)||1.5)),vertical=Math.max(.1,(Math.max(1,Number(p.levels)||1)-1)*Math.max(.1,Number(p.levelHeight)||1.5)),fork=Math.max(.01,Number(p.forkStroke)||.94);return[{name:'X축 주행',distance:horizontal,speed:Number(p.travelSpeed)||2.5,accelerationKey:'travelAcceleration',decelerationKey:'travelDeceleration'},{name:'Y축 승강',distance:vertical,speed:Math.max(Number(p.liftSpeed)||1,Number(p.downSpeed)||1),accelerationKey:'liftAcceleration',decelerationKey:'liftDeceleration'},{name:'Z축 포크',distance:fork,speed:Number(p.forkSpeed)||.65,accelerationKey:'forkAcceleration',decelerationKey:'forkDeceleration'}];}
function applyAutomaticMotionDynamics(item){if(item.parameters?.autoMotionTuning===0)return;if(['asrs','stackerCrane'].includes(item.type)){for(const axis of storageMotionAxes(item)){const values=recommendedMotionDynamics(axis.distance,axis.speed);item.parameters[axis.accelerationKey]=values.acceleration;item.parameters[axis.decelerationKey]=values.deceleration;}return;}const distance=equipmentProfileDistance(item);if(distance)Object.assign(item.parameters,recommendedMotionDynamics(distance,motionConfigFor(item).targetSpeed));}
function appendMotionProfileGraphs(items,selectedId){for(const item of items){const card=cadParameterSection.querySelector(`[data-parameter-card="${CSS.escape(item.id)}"]`),distance=equipmentProfileDistance(item);if(!card||!distance)continue;const automatic=item.parameters?.autoMotionTuning!==0,toggle=document.createElement('label'),toggleText=document.createElement('span'),checkbox=document.createElement('input');toggle.className='motion-auto-toggle';toggleText.textContent='가속·감속 자동 설정';checkbox.type='checkbox';checkbox.checked=automatic;checkbox.dataset.parameterCheckbox='autoMotionTuning';checkbox.dataset.parameter='autoMotionTuning';checkbox.dataset.checkboxEquipmentId=item.id;toggle.append(toggleText,checkbox);card.querySelector('[data-parameter="acceleration"]')?.closest('label')?.before(toggle);for(const key of ['acceleration','deceleration']){const input=card.querySelector(`[data-parameter="${key}"]`);if(input){input.readOnly=automatic;input.title=automatic?'속도와 이동거리에 맞춰 자동 계산됩니다. 자동 설정을 끄면 직접 입력할 수 있습니다.':'';}}const config=motionConfigFor(item),summary=motionProfileSummary(distance,config),total=Math.max(.001,summary.total),left=12,width=216,x1=left+width*summary.t1/total,x2=x1+width*summary.t2/total,peakY=18,baseY=72,box=document.createElement('div');box.className='motion-profile-card';box.hidden=item.id!==selectedId;box.innerHTML=`<strong>예상 구동 속도 프로파일</strong><svg viewBox="0 0 240 112" role="img" aria-label="가속 정속 감속 속도 그래프"><line x1="${left}" y1="${baseY}" x2="${left+width}" y2="${baseY}"/><line x1="${x1.toFixed(1)}" y1="${peakY}" x2="${x1.toFixed(1)}" y2="92"/><line x1="${x2.toFixed(1)}" y1="${peakY}" x2="${x2.toFixed(1)}" y2="92"/><path d="M${left} ${baseY} L${x1.toFixed(1)} ${peakY} L${x2.toFixed(1)} ${peakY} L${left+width} ${baseY}"/><text x="${Math.max(14,x1/2-4).toFixed(1)}" y="48">s1</text><text x="${((x1+x2)/2-4).toFixed(1)}" y="48">s2</text><text x="${((x2+left+width)/2-4).toFixed(1)}" y="48">s3</text><text x="${Math.max(12,x1/2-5).toFixed(1)}" y="88">t1</text><text x="${((x1+x2)/2-5).toFixed(1)}" y="88">t2</text><text x="${((x2+left+width)/2-5).toFixed(1)}" y="88">t3</text><text x="${Math.max(14,(x1+x2)/2-28).toFixed(1)}" y="12">Vt ${config.targetSpeed.toFixed(2)}m/s</text><text x="92" y="106">T1 ${summary.total.toFixed(2)}초</text></svg><small>${summary.t2>0?'안정형 사다리꼴':'거리 부족 삼각형'} · 거리 ${summary.distance.toFixed(2)}m · 최고 ${summary.peakSpeed.toFixed(2)}m/s</small><small>가속 ${config.acceleration.toFixed(2)}m/s² (${summary.t1.toFixed(2)}초) · 정속 ${summary.t2.toFixed(2)}초 · 감속 ${config.deceleration.toFixed(2)}m/s² (${summary.t3.toFixed(2)}초)</small>`;card.append(box);}}
function appendEquipmentMotionProfiles(items,selectedId){appendMotionProfileGraphs(items.filter(item=>!['asrs','stackerCrane'].includes(item.type)),selectedId);for(const item of items.filter(item=>['asrs','stackerCrane'].includes(item.type))){const card=cadParameterSection.querySelector(`[data-parameter-card="${CSS.escape(item.id)}"]`);if(!card)continue;const automatic=item.parameters?.autoMotionTuning!==0,toggle=document.createElement('label');toggle.className='motion-auto-toggle';toggle.innerHTML=`<span>X·Y·Z축 가감속 자동 설정</span><input type="checkbox" ${automatic?'checked':''} data-parameter-checkbox="autoMotionTuning" data-parameter="autoMotionTuning" data-checkbox-equipment-id="${item.id}">`;card.querySelector('[data-parameter="travelAcceleration"]')?.closest('label')?.before(toggle);for(const axis of storageMotionAxes(item)){for(const key of [axis.accelerationKey,axis.decelerationKey]){const input=card.querySelector(`[data-parameter="${key}"]`);if(input){input.readOnly=automatic;input.title=automatic?'해당 축의 최대 이동거리와 속도로 자동 계산됩니다.':'';}}const config={targetSpeed:axis.speed,acceleration:Number(item.parameters[axis.accelerationKey]),deceleration:Number(item.parameters[axis.decelerationKey]),motionProfile:'trapezoidal'},summary=motionProfileSummary(axis.distance,config),total=Math.max(.001,summary.total),x1=12+216*summary.t1/total,x2=x1+216*summary.t2/total,box=document.createElement('div');box.className='motion-profile-card axis-profile';box.hidden=item.id!==selectedId;box.innerHTML=`<strong>${axis.name} 속도 프로파일</strong><svg viewBox="0 0 240 112"><line x1="12" y1="72" x2="228" y2="72"/><line x1="${x1.toFixed(1)}" y1="18" x2="${x1.toFixed(1)}" y2="92"/><line x1="${x2.toFixed(1)}" y1="18" x2="${x2.toFixed(1)}" y2="92"/><path d="M12 72 L${x1.toFixed(1)} 18 L${x2.toFixed(1)} 18 L228 72"/><text x="35" y="48">s1</text><text x="112" y="48">s2</text><text x="195" y="48">s3</text><text x="35" y="88">t1</text><text x="112" y="88">t2</text><text x="195" y="88">t3</text><text x="86" y="12">Vt ${axis.speed.toFixed(2)}m/s</text><text x="92" y="106">T1 ${summary.total.toFixed(2)}초</text></svg><small>절대 목표 위치 거리 ${axis.distance.toFixed(2)}m · ${summary.t2>0?'정속구간 확보':'목표속도 미도달'}</small><small>가속 ${config.acceleration.toFixed(2)} · 감속 ${config.deceleration.toFixed(2)}m/s²</small>`;card.append(box);}}}
function wrapParameterGroup(card,title,nodes,hint=''){const valid=[...new Set(nodes.filter(Boolean))];if(!valid.length)return;const group=document.createElement('div'),heading=document.createElement('strong');group.className='parameter-option-group';heading.className='parameter-option-title';heading.textContent=title;valid[0].before(group);group.append(heading,...valid);if(hint){const note=document.createElement('small');note.className='parameter-option-hint';note.textContent=hint;group.append(note);}return group;}
function groupDependentParameterControls(items){for(const item of items){const card=cadParameterSection.querySelector(`[data-parameter-card="${CSS.escape(item.id)}"]`);if(!card)continue;const motionToggle=card.querySelector('.motion-auto-toggle'),motionKeys=['acceleration','deceleration','travelAcceleration','travelDeceleration','liftAcceleration','liftDeceleration','forkAcceleration','forkDeceleration'],motionLabels=motionKeys.map(key=>card.querySelector(`[data-parameter="${key}"]`)?.closest('label')),profiles=[...card.querySelectorAll('.motion-profile-card')],motionGroup=wrapParameterGroup(card,'구동 속도 프로파일 설정',[motionToggle,...motionLabels,...profiles],'체크 시 속도와 실제 이동거리로 가속도·감속도를 자동 계산합니다. 해제하면 아래 값을 직접 입력합니다.');if(motionGroup&&profiles.length){const expand=document.createElement('button');expand.type='button';expand.className='visual-expand-button';expand.dataset.expandMotion=item.id;expand.textContent='프로파일 확대 보기';motionGroup.append(expand);}if(item.type==='conveyor'){const toggle=card.querySelector('[data-parameter-checkbox="continuousHandover"]')?.closest('label'),delay=card.querySelector('[data-parameter="handoverDelay"]')?.closest('label'),group=wrapParameterGroup(card,'다음 설비 인계 방식',[toggle,delay],'체크하면 승인 즉시 연속 인계합니다. 해제하면 설정한 대기시간 후 인계합니다.');const delayInput=delay?.querySelector('input');if(delayInput)delayInput.disabled=Boolean(toggle?.querySelector('input')?.checked);group?.classList.toggle('option-disabled',Boolean(toggle?.querySelector('input')?.checked));}const batch=card.querySelector('.fork-flow-selector:has([data-parameter-checkbox="batchReleaseEnabled"])');if(batch){batch.classList.add('parameter-option-group');const amount=batch.querySelector('[data-parameter="releaseBatchSize"]');if(amount)amount.disabled=!batch.querySelector('[data-parameter-checkbox="batchReleaseEnabled"]')?.checked;}if(item.type==='forkingDevice'){const role=card.querySelector('.fork-role-toggle'),ratio=card.querySelector('[data-parameter="output1Ratio"]')?.closest('label'),selector=card.querySelector('.fork-flow-selector'),group=wrapParameterGroup(card,'분배 포킹 조건',[role,ratio,selector],'체크한 경우에만 선택한 출발 라인의 물류를 설정 비율로 순차 분배합니다.');const enabled=role?.querySelector('input')?.checked!==false;if(ratio?.querySelector('input'))ratio.querySelector('input').disabled=!enabled;group?.classList.toggle('option-disabled',!enabled);}}}
function appendCommonApplyControls(items){for(const card of cadParameterSection.querySelectorAll('[data-parameter-card]')){const item=items.find(entry=>entry.id===card.dataset.parameterCard);if(!item)continue;const all=document.createElement('button');all.type='button';all.className='apply-common-all';all.textContent='이 설비 파라미터 전체 공통 적용';all.dataset.applyEquipment=item.id;card.querySelector('summary')?.after(all);for(const input of card.querySelectorAll('[data-parameter]')){if(input.readOnly)continue;const button=document.createElement('button');button.type='button';button.className='apply-common-one';button.textContent='공통 적용';button.title='같은 종류의 모든 설비에 이 값 적용';button.dataset.applyEquipment=item.id;button.dataset.applyParameter=input.dataset.parameter;(input.closest('span')||input.closest('label'))?.append(button);}}}
function renderCadEquipmentParameters(selectedId=selectedEquipment?.id){
  const items=layout.equipment.filter(item=>item.source?.origin==='dxf'&&item.reviewStatus==='approved'),counts={};
  const legacyConveyor=items.find(item=>item.type==='conveyor'&&(item.parameters?.cargoLength||item.parameters?.cargoWidth));if(!layout.cargoSpec)layout.cargoSpec={length:Number(legacyConveyor?.parameters?.cargoLength||1.2),width:Number(legacyConveyor?.parameters?.cargoWidth||.8)};ensureCargoSpecMm();
  for(const item of items){ensureDynamicParameters(item);applyAutomaticMotionDynamics(item);counts[item.type]=(counts[item.type]||0)+1;}
  const active=items.length>0;$('defaultEquipmentControls').hidden=active;$('dynamicEquipmentControls').hidden=!active;cadParameterSection.hidden=!active;
  const groups=Object.entries(Object.groupBy?Object.groupBy(items,item=>item.type):items.reduce((result,item)=>((result[item.type]??=[]).push(item),result),{}));
  cadParameterSection.innerHTML=active?`<h2>레이아웃 설비 파라미터</h2><details class="equipment-parameter-card selected" open><summary>공통 물류 규격</summary><label>물류 길이(mm)<span><input type="number" step="1" min="1" data-cargo-parameter="length" value="${layout.cargoSpec.length}"></span></label><label>물류 폭(mm)<span><input type="number" step="1" min="1" data-cargo-parameter="width" value="${layout.cargoSpec.width}"></span></label><label>물류 무게(kg)<span><input type="number" step="0.1" min="0.01" data-cargo-parameter="weight" value="${layout.cargoSpec.weight}"></span></label></details><p class="equipment-counts">${selectedId?'선택 설비의 파라미터가 펼쳐졌습니다 · ':''}${Object.entries(counts).map(([type,count])=>`${type.toUpperCase()} ${count}대`).join(' · ')}</p>`+groups.map(([type,equipment])=>`<div class="equipment-type-group"><h3>${type.toUpperCase()} <small>${equipment.length}대</small></h3>${equipment.map(item=>`<details class="equipment-parameter-card${item.id===selectedId?' selected':''}" data-parameter-card="${item.id}" ${item.id===selectedId?'open':''}><summary>${item.name}</summary>${parameterFieldsFor(item).map(field=>`<label>${field.label}<span><input type="number" step="0.1" ${field.min!==undefined?`min="${field.min}"`:''} ${field.max!==undefined?`max="${field.max}"`:''} ${field.readOnly?'readonly':''} data-equipment-id="${item.id}" data-parameter="${field.key}" value="${field.value}"></span></label>`).join('')}</details>`).join('')}</div>`).join(''):'';
  if(active){appendConveyorHandoverControls(items);appendForkParameterControls(items);appendAsrsBatchControls(items);appendSourceCargoControls(items);appendEquipmentMotionProfiles(items,selectedId);groupDependentParameterControls(items);appendCommonApplyControls(items);}
  if(selectedId)requestAnimationFrame(()=>cadParameterSection.querySelector(`[data-parameter-card="${CSS.escape(selectedId)}"]`)?.scrollIntoView({block:'nearest',behavior:'smooth'}));
}
cadParameterSection.addEventListener('change',event=>{const checkbox=event.target.closest('[data-parameter-checkbox]');if(!checkbox)return;const item=layout.equipment.find(entry=>entry.id===checkbox.dataset.checkboxEquipmentId);if(!item)return;item.parameters??={};item.parameters[checkbox.dataset.parameterCheckbox]=checkbox.checked?1:0;if(checkbox.dataset.parameterCheckbox==='autoMotionTuning')applyAutomaticMotionDynamics(item);resetEngine();renderCadEquipmentParameters(item.id);});
cadParameterSection.addEventListener('change',event=>{const input=event.target.closest('[data-source-cargo-type]');if(!input)return;const item=layout.equipment.find(entry=>entry.id===input.dataset.sourceCargoType);if(!item)return;item.parameters??={};item.parameters.cargoType=input.value.trim()||item.name||'물류';input.value=item.parameters.cargoType;resetEngine();});
cadParameterSection.addEventListener('change',event=>{const enabled=event.target.closest('[data-fork-enabled]');if(enabled){const item=layout.equipment.find(entry=>entry.id===enabled.dataset.forkId);if(item){item.parameters??={};item.parameters.distributionEnabled=enabled.checked;resetEngine();renderCadEquipmentParameters(item.id);}return;}const common=event.target.closest('[data-cargo-parameter]');if(common){layout.cargoSpec??={length:1200,width:800,weight:100,unit:'mm'};const cargoKey=common.dataset.cargoParameter;layout.cargoSpec[cargoKey]=cargoKey==='weight'?Math.max(.01,Number(common.value)||.01):Math.max(1,Math.round(Number(common.value)||1));layout.cargoSpec.unit='mm';common.value=layout.cargoSpec[common.dataset.cargoParameter];resetEngine();return;}const input=event.target.closest('[data-equipment-id]');if(!input||input.readOnly)return;const item=layout.equipment.find(entry=>entry.id===input.dataset.equipmentId);if(item){item.parameters??={};const binary=['simultaneousMotion','returnHome','motionProfile'].includes(input.dataset.parameter),integer=binary||['levels','rows','columns','productTypes','stackerCount','releaseBatchSize','infeedColumn','infeedLevel','outfeedColumn','outfeedLevel'].includes(input.dataset.parameter),value=Number(input.value);item.parameters[input.dataset.parameter]=integer?Math.max(binary?0:1,Math.round(value||0)):value;if(input.dataset.parameter==='length')item.parameters.length=Math.max(.1,item.parameters.length||.1);if(input.dataset.parameter==='length'){item.source??={};item.source.parameterLengthUnit='m';}input.value=item.parameters[input.dataset.parameter];if(engine instanceof CadFlowEngine)engine.hotReloadEquipment(item);else resetEngine();renderer.draw(engine.state);if(['levels','rows','columns','productTypes','stackerCount'].includes(input.dataset.parameter))resetEngine();renderCadEquipmentParameters(item.id);}});
cadParameterSection.addEventListener('change',event=>{const input=event.target.closest('[data-equipment-id]');if(!input||!['speed','lineSpeed','travelSpeed','liftSpeed','receiveSpeed','transferSpeed','length','shuttleDistance','travelDistance','liftHeight','strokeDistance','columns','columnPitch'].includes(input.dataset.parameter))return;const item=layout.equipment.find(entry=>entry.id===input.dataset.equipmentId);if(!item||item.parameters?.autoMotionTuning===0)return;applyAutomaticMotionDynamics(item);if(engine instanceof CadFlowEngine)engine.hotReloadEquipment(item);else resetEngine();renderCadEquipmentParameters(item.id);});
cadParameterSection.addEventListener('change',event=>{const input=event.target.closest('[data-equipment-id]');if(!input||!['downSpeed','forkSpeed','forkStroke','levels','levelHeight'].includes(input.dataset.parameter))return;const item=layout.equipment.find(entry=>entry.id===input.dataset.equipmentId);if(!item||!['asrs','stackerCrane'].includes(item.type)||item.parameters?.autoMotionTuning===0)return;applyAutomaticMotionDynamics(item);if(engine instanceof CadFlowEngine)engine.hotReloadEquipment(item);else resetEngine();renderCadEquipmentParameters(item.id);});
cadParameterSection.addEventListener('click',event=>{const button=event.target.closest('[data-apply-equipment]');if(!button)return;const source=layout.equipment.find(entry=>entry.id===button.dataset.applyEquipment);if(!source)return;const keys=button.dataset.applyParameter?[button.dataset.applyParameter]:Object.keys(source.parameters||{});for(const target of layout.equipment.filter(entry=>entry.id!==source.id&&entry.type===source.type)){target.parameters??={};for(const key of keys)if(source.parameters?.[key]!==undefined)target.parameters[key]=structuredClone(source.parameters[key]);if(source.type==='conveyor'&&keys.includes('length')){target.source??={};target.source.parameterLengthUnit='m';}}resetEngine();renderCadEquipmentParameters(source.id);});
cadParameterSection.addEventListener('click',event=>{const button=event.target.closest('[data-fork-flow]');if(!button)return;const item=layout.equipment.find(entry=>entry.id===button.dataset.forkId);if(!item)return;const names=detectedFlowNames();item.parameters??={};const selected=new Set(Array.isArray(item.parameters.distributionFlowKeys)&&item.parameters.distributionFlowKeys.length?item.parameters.distributionFlowKeys:names);selected.has(button.dataset.forkFlow)?selected.delete(button.dataset.forkFlow):selected.add(button.dataset.forkFlow);item.parameters.distributionFlowKeys=[...selected];resetEngine();renderCadEquipmentParameters(item.id);});
$('cadCandidates').addEventListener('click',event=>{
  const button=event.target.closest('[data-cad-action]');if(!button)return;const action=button.dataset.cadAction,id=button.dataset.id;
  const selected=action==='approve-all'?pendingCadCandidates:pendingCadCandidates.filter(item=>item.id===id);
  if(action==='approve'||action==='approve-all'){
    const importId=selected[0]?.source?.importId;
    if(importId&&layout.cadActiveImportId!==importId){layout.equipment=layout.equipment.filter(item=>item.source?.origin!=='dxf');layout.cadActiveImportId=importId;layout.displayMode='cad';}
    for(const item of selected){item.reviewStatus='approved';layout.equipment.push(item);}
  }
  if(action==='approve-all'||action==='discard-all')pendingCadCandidates=[];else pendingCadCandidates=pendingCadCandidates.filter(item=>item.id!==id);
  renderer.setLayout(layout);if(action==='approve'||action==='approve-all')resetEngine();else renderer.draw(engine.state);renderCadCandidates();renderCadEquipmentParameters();
  if(action==='approve'||action==='approve-all'){$('cadStatusTitle').textContent='설비 반영 완료';$('cadStatusText').textContent=`${selected.length}개 설비를 레이아웃에 배치했습니다. 편집 모드에서 위치와 파라미터를 보정할 수 있습니다.`;}
  else if(action==='discard-all'){$('cadStatusTitle').textContent='후보 제외 완료';$('cadStatusText').textContent='분석 후보를 모두 제외했습니다.';}
});
document.querySelectorAll('[data-add]').forEach(button=>button.addEventListener('click',()=>editor.beginPlacement(button.dataset.add)));
$('newLayoutProject').addEventListener('click',()=>{layout=cloneLayout(emptyLayout);layout.id=`manual-${Date.now()}`;layout.name='새 물류 시뮬레이션';setProjectEmpty(false);renderer.setLayout(layout);$('editorTools').hidden=false;editor.setEnabled(true);$('editorToggle').textContent='편집 종료';resetEngine();renderCadEquipmentParameters();editor.fitView();});
$('connectEquipment').addEventListener('click',()=>{const active=!editor.connecting;editor.setConnectionMode(active);$('connectEquipment').classList.toggle('active',active);$('connectionHint').hidden=!active;$('connectionHint').textContent='시작 설비의 연결점을 누른 채 도착 설비 연결점까지 드래그하세요.';});
$('resetView').addEventListener('click',()=>editor.fitView());
$('deleteEquipment').addEventListener('click',()=>{if(selectedEquipment&&editor.remove(selectedEquipment.id)){resetEngine();renderCadEquipmentParameters();}});
$('deleteConnection').addEventListener('click',deleteSelectedConnection);$('contextDeleteConnection').addEventListener('click',deleteSelectedConnection);document.addEventListener('pointerdown',event=>{if(!event.target.closest('#edgeContextMenu')&&!event.target.closest('#layoutCanvas'))$('edgeContextMenu').hidden=true;});
for(const id of ['propName','propX','propY','propRotation']) $(id).addEventListener('change',()=>{if(!selectedEquipment)return;selectedEquipment.name=$('propName').value||selectedEquipment.name;selectedEquipment.x=Math.round(Number($('propX').value)||0);selectedEquipment.y=Math.round(Number($('propY').value)||0);selectedEquipment.rotation=((Number($('propRotation').value)||0)%360+360)%360;$('propX').value=selectedEquipment.x;$('propY').value=selectedEquipment.y;$('propRotation').value=selectedEquipment.rotation;refreshEquipmentConnections(layout,selectedEquipment.id);renderer.draw(engine.state);});
function rotateSelected(delta){if(!selectedEquipment)return;selectedEquipment.rotation=((Number(selectedEquipment.rotation)||0)+delta+360)%360;$('propRotation').value=selectedEquipment.rotation;refreshEquipmentConnections(layout,selectedEquipment.id);renderer.draw(engine.state);}
$('rotateLeft').addEventListener('click',()=>rotateSelected(-90));$('rotateRight').addEventListener('click',()=>rotateSelected(90));
$('layoutFile').addEventListener('change',async event=>{
  const file=event.target.files[0]; if(!file)return;
  try {const candidate=JSON.parse(await file.text()), check=validateLayout(candidate);if(!check.valid)throw new Error(check.errors.join(' '));layout=candidate;ensureCargoSpecMm(layout);writeParams(candidate.simulationParams);renderer.setLayout(layout);await renderer.setBackground(layout.background?.dataUrl||null);setProjectEmpty(false);resetEngine();renderCadEquipmentParameters();$('layoutName').textContent=layout.name;selectEquipment(null);editor.fitView();}
  catch(error){$('validation').textContent='레이아웃 불러오기 실패: '+error.message;} finally{event.target.value='';}
});
writeParams(defaultParams);setProjectEmpty(true);syncFlowView();renderer.draw({t:0,cadTokens:[],source:[],product:[],locks:{},robot:{phase:'idle'}});renderEvents();
