import { asrsOperationSnapshot } from './engine.js';

export const isoPoint=(origin,column,level,depth=0,cellW=15,cellH=10,depthW=5)=>({x:origin.x+column*cellW+depth*depthW,y:origin.y-level*cellH-depth*depthW*.55});

export function asrsSceneModel(equipment,state,colorFor){
  const asrs=state?.asrs,zones=Object.entries(asrs?.zones||{}),columns=Math.max(1,Number(asrs?.columns)||8),levels=Math.max(1,Number(asrs?.levels)||4),rows=Math.max(1,Number(asrs?.rows)||2),active=(state?.cadTokens||[]).filter(token=>token.nodeId===asrs?.equipmentId&&!token.edge&&['putaway','retrieval'].includes(token.asrsPhase));
  return{columns,levels,rows,zones:zones.map(([name,zone],index)=>{const token=active.find(entry=>entry.flowKey===name),operation=asrsOperationSnapshot(equipment,token,state?.t||0),column=Math.max(0,Math.min(columns-1,(operation.x||0)-1)),level=Math.max(0,Math.min(levels-1,(operation.y||0)-1));return{name,zone,index,color:colorFor(name,index),operation,column,level};})};
}

const polygon=(ctx,points,fill,stroke)=>{ctx.beginPath();points.forEach((point,index)=>index?ctx.lineTo(point.x,point.y):ctx.moveTo(point.x,point.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.stroke();};

export function drawAsrsScene(canvas,equipment,state,colorFor){
  if(!canvas||!equipment||!state?.asrs)return;const dpr=Math.max(1,globalThis.devicePixelRatio||1),width=Math.max(280,canvas.clientWidth||300),model=asrsSceneModel(equipment,state,colorFor),laneH=105,height=Math.max(130,model.zones.length*laneH+20);canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.height=`${height}px`;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,width,height);ctx.lineWidth=1;
  model.zones.forEach(entry=>{const top=entry.index*laneH+8,origin={x:22,y:top+76},rackW=Math.min(160,width-105),cellW=rackW/model.columns,cellH=Math.min(13,54/model.levels),depth=Math.min(2,model.rows);ctx.fillStyle='rgba(5,17,27,.92)';ctx.fillRect(4,top,width-8,laneH-6);ctx.strokeStyle='rgba(68,119,150,.45)';ctx.strokeRect(4,top,width-8,laneH-6);
    ctx.font='bold 9px monospace';ctx.fillStyle=entry.color;ctx.fillText(entry.name,12,top+13);ctx.fillStyle='#d8f3ff';ctx.textAlign='right';ctx.fillText(`${entry.zone.inventory}/${entry.zone.capacity}`,width-12,top+13);ctx.textAlign='left';
    for(let depthIndex=depth-1;depthIndex>=0;depthIndex--)for(let column=0;column<model.columns;column++)for(let level=0;level<model.levels;level++){const p=isoPoint(origin,column,level,depthIndex,cellW,cellH,5),occupied=column*model.levels*model.rows+level*model.rows+depthIndex<entry.zone.inventory,front=[p,{x:p.x+cellW-1,y:p.y},{x:p.x+cellW-1,y:p.y-cellH+1},{x:p.x,y:p.y-cellH+1}],side=[front[1],{x:front[1].x+5,y:front[1].y-3},{x:front[2].x+5,y:front[2].y-3},front[2]];polygon(ctx,side,occupied?`${entry.color}55`:'rgba(22,49,65,.55)','rgba(105,158,185,.28)');polygon(ctx,front,occupied?`${entry.color}88`:'rgba(12,35,49,.9)','rgba(105,158,185,.38)');}
    const aisleX=origin.x+entry.column*cellW+cellW*.5,carY=origin.y-entry.level*cellH-cellH*.5,active=entry.operation.status!=='waiting',pulse=Math.floor((state.t||0)*3)%2===0,activityColor=entry.operation.status==='outbound'?'#ff754d':'#00d4ff';ctx.shadowBlur=active&&pulse?12:3;ctx.shadowColor=activityColor;ctx.strokeStyle=active?activityColor:'#41677d';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(aisleX,top+20);ctx.lineTo(aisleX,origin.y+5);ctx.stroke();ctx.fillStyle=active?activityColor:'#315264';ctx.fillRect(aisleX-7,carY-4,14,8);if(active){ctx.fillStyle=entry.color;ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.fillRect(aisleX-5,carY-3,10,6);ctx.strokeRect(aisleX-5,carY-3,10,6);}ctx.shadowBlur=0;
    ctx.font='8px monospace';ctx.fillStyle=active?activityColor:'#63849a';ctx.fillText(entry.operation.label,12,top+94);ctx.fillStyle='#8fb0c2';ctx.fillText(entry.operation.detail,55,top+94);ctx.fillStyle='#54758a';ctx.textAlign='right';ctx.fillText(active?`${Math.round(entry.operation.progress*100)}%`:'',width-12,top+94);ctx.textAlign='left';});
}
