import { asrsModeChangeSnapshot, asrsOperationSnapshot } from './engine.js';

export const isoPoint=(origin,column,level,depth=0,cellW=15,cellH=10,depthW=5)=>({x:origin.x+column*cellW+depth*depthW,y:origin.y-level*cellH-depth*depthW*.55});

export const asrsDepthPresentation=(operation,rows)=>{const targetDepth=Math.max(0,Math.min(Math.max(1,rows)-1,Number(operation?.target?.row)||0)),rearTarget=targetDepth>0&&operation?.status!=='waiting',depthGap=rearTarget?12:5,forkProgress=Math.max(0,Math.min(1,Number(operation?.forkProgress)||0)),cargoAtCell=operation?.phase==='fork',cargoScale=cargoAtCell?(operation?.status==='outbound'?forkProgress:1-forkProgress):Math.max(0,Math.min(1,Number(operation?.cargoScale??1)));return{targetDepth,rearTarget,depthGap,frontAlpha:rearTarget?.28:1,cargoAtCell,cargoScale};};

export function asrsSceneModel(equipment,state,colorFor,cargoColorFor=colorFor){
  const asrs=state?.asrs,rackZones=Object.entries(asrs?.zones||{}),stackers=Object.entries(asrs?.stackers||{}),views=stackers.length?stackers:rackZones,columns=Math.max(1,Number(asrs?.columns)||8),levels=Math.max(1,Number(asrs?.levels)||4),rows=Math.max(1,Number(asrs?.rows)||2),active=(state?.cadTokens||[]).filter(token=>token.nodeId===asrs?.equipmentId&&!token.edge&&['putaway','retrieval'].includes(token.asrsPhase));
  return{columns,levels,rows,zones:views.map(([stackerKey,stacker],index)=>{const [zoneName,zone]=rackZones.find(([name])=>name===stackerKey)||rackZones[index]||[stackerKey,{inventory:0,capacity:columns*levels*rows}],token=active.find(entry=>(entry.stackerKey||entry.flowKey)===stackerKey),modeState=stackers.length?stacker:asrs?.lineStates?.[stackerKey],operation=token?asrsOperationSnapshot(equipment,token,state?.t||0):asrsModeChangeSnapshot(equipment,modeState,state?.t||0)||asrsOperationSnapshot(equipment,null,state?.t||0),target=operation.target||{column:0,level:0,row:0},stored=(state?.cadTokens||[]).filter(entry=>entry.nodeId===asrs?.equipmentId&&entry.flowKey===zoneName&&entry.asrsTarget),slotCargoTypes=Object.fromEntries(stored.map(entry=>[entry.asrsTarget.index,entry.cargoType||entry.flowKey]));return{name:stackerKey,stackerId:stacker?.id||`stacker-${index+1}`,storageZone:zoneName,zone,index,color:colorFor(zoneName,index),cargoType:token?.cargoType||stacker?.cargoType||stackerKey,cargoColor:cargoColorFor(token?.cargoType||stacker?.cargoType||stackerKey,token?.flowIndex??index),slotCargoTypes,operation,target,column:Math.max(0,Math.min(columns-1,operation.x||0)),level:Math.max(0,Math.min(levels-1,operation.y||0))};})};
}

const polygon=(ctx,points,fill,stroke,lineWidth=1)=>{ctx.beginPath();points.forEach((point,index)=>index?ctx.lineTo(point.x,point.y):ctx.moveTo(point.x,point.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=lineWidth;ctx.stroke();};
const cube=(ctx,x,y,w,h,depth,color,alpha=.9)=>{const front=[{x,y},{x:x+w,y},{x:x+w,y:y-h},{x,y:y-h}],side=[front[1],{x:x+w+depth,y:y-depth*.55},{x:x+w+depth,y:y-h-depth*.55},front[2]],top=[front[3],front[2],side[2],{x:x+depth,y:y-h-depth*.55}];polygon(ctx,side,`${color}66`,'rgba(220,247,255,.7)');polygon(ctx,top,`${color}aa`,'rgba(220,247,255,.8)');polygon(ctx,front,`${color}${Math.round(alpha*255).toString(16).padStart(2,'0')}`,'rgba(255,255,255,.9)');};

export function drawAsrsScene(canvas,equipment,state,colorFor,cargoColorFor=colorFor){
  if(!canvas||!equipment||!state?.asrs)return;
  const dpr=Math.max(1,globalThis.devicePixelRatio||1),width=Math.max(300,canvas.clientWidth||320),model=asrsSceneModel(equipment,state,colorFor,cargoColorFor),laneH=134,height=Math.max(150,model.zones.length*laneH+16);canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.height=`${height}px`;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,width,height);
  model.zones.forEach(entry=>{const top=entry.index*laneH+7,origin={x:20,y:top+91},rackW=Math.min(175,width-120),cellW=rackW/model.columns,cellH=Math.min(15,62/model.levels),depth=Math.min(2,model.rows),op=entry.operation,active=op.status!=='waiting',depthView=asrsDepthPresentation(op,model.rows),activityColor=op.status==='outbound'?'#ff754d':'#00d4ff',pulse=.65+.35*Math.sin((state.t||0)*5);
    ctx.fillStyle='rgba(4,15,25,.96)';ctx.fillRect(4,top,width-8,laneH-5);ctx.strokeStyle=active?activityColor:'rgba(68,119,150,.45)';ctx.lineWidth=active?1.5:1;ctx.strokeRect(4,top,width-8,laneH-5);
    ctx.font='bold 9px monospace';ctx.fillStyle=entry.color;ctx.fillText(entry.name,12,top+13);ctx.fillStyle='#d8f3ff';ctx.textAlign='right';ctx.fillText(`${entry.zone.inventory}/${entry.zone.capacity}`,width-12,top+13);if(active){ctx.fillStyle=activityColor;ctx.fillText(`목표 ${entry.target.column+1}열-${entry.target.level+1}단-${entry.target.row+1}행`,width-12,top+25);}ctx.textAlign='left';
    for(let depthIndex=depth-1;depthIndex>=0;depthIndex--)for(let column=0;column<model.columns;column++)for(let level=0;level<model.levels;level++){const p=isoPoint(origin,column,level,depthIndex,cellW,cellH,depthView.depthGap),slot=column*model.levels*model.rows+level*model.rows+depthIndex,occupied=Array.isArray(entry.zone.occupiedSlots)?Boolean(entry.zone.occupiedSlots[slot]):slot<entry.zone.inventory,isTarget=active&&column===entry.target.column&&level===entry.target.level&&depthIndex===Math.min(depth-1,entry.target.row||0),cellCargoType=entry.slotCargoTypes[slot],cellColor=cellCargoType?cargoColorFor(cellCargoType,slot):entry.color,front=[p,{x:p.x+cellW-1,y:p.y},{x:p.x+cellW-1,y:p.y-cellH+1},{x:p.x,y:p.y-cellH+1}],side=[front[1],{x:front[1].x+depthView.depthGap,y:front[1].y-depthView.depthGap*.55},{x:front[2].x+depthView.depthGap,y:front[2].y-depthView.depthGap*.55},front[2]];ctx.save();if(depthView.rearTarget&&depthIndex===0&&!isTarget)ctx.globalAlpha=depthView.frontAlpha;polygon(ctx,side,occupied?`${cellColor}55`:'rgba(22,49,65,.55)',isTarget?activityColor:'rgba(105,158,185,.28)',isTarget?2:1);polygon(ctx,front,occupied?`${cellColor}88`:'rgba(12,35,49,.9)',isTarget?entry.color:'rgba(105,158,185,.38)',isTarget?2:1);ctx.restore();if(isTarget){ctx.save();ctx.globalAlpha=pulse;ctx.strokeStyle=entry.color;ctx.lineWidth=3;ctx.strokeRect(p.x-2,p.y-cellH-1,cellW+3,cellH+3);ctx.restore();}}
    const parameters=equipment.parameters||{},inColumn=Math.max(0,Math.min(model.columns-1,(Number(parameters.infeedColumn)||1)-1)),inLevel=Math.max(0,Math.min(model.levels-1,(Number(parameters.infeedLevel)||1)-1)),outColumn=Math.max(0,Math.min(model.columns-1,(Number(parameters.outfeedColumn)||model.columns)-1)),outLevel=Math.max(0,Math.min(model.levels-1,(Number(parameters.outfeedLevel)||1)-1)),inPoint=isoPoint(origin,inColumn,inLevel,0,cellW,cellH,depthView.depthGap),outPoint=isoPoint(origin,outColumn,outLevel,0,cellW,cellH,depthView.depthGap),aisleX=origin.x+entry.column*cellW+cellW*.5,carY=origin.y-entry.level*cellH-cellH*.5,targetPoint=isoPoint(origin,entry.target.column,entry.target.level,depthView.targetDepth,cellW,cellH,depthView.depthGap),forkDepth=active&&op.phase==='fork'?op.forkExtension*(13+depthView.targetDepth*depthView.depthGap):0;
    ctx.font='bold 7px monospace';ctx.fillStyle='#00d4ff';ctx.fillText('IN',inPoint.x,inPoint.y+9);ctx.fillStyle='#ff754d';ctx.fillText('OUT',outPoint.x,outPoint.y+9);
    ctx.shadowBlur=active?8*pulse:2;ctx.shadowColor=activityColor;ctx.strokeStyle=active?activityColor:'#41677d';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(aisleX,top+22);ctx.lineTo(aisleX,origin.y+5);ctx.stroke();ctx.fillStyle=active?activityColor:'#315264';ctx.fillRect(aisleX-8,carY-5,16,10);ctx.shadowBlur=0;
    if(active){ctx.strokeStyle='#fff2a8';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(aisleX,carY);ctx.lineTo(aisleX+forkDepth,carY-forkDepth*.55);ctx.stroke();if(depthView.cargoAtCell&&depthView.cargoScale>0){const baseW=Math.max(7,cellW*.5),baseH=Math.max(5,cellH*.55),scaledW=baseW*depthView.cargoScale,scaledH=baseH*depthView.cargoScale,centerX=targetPoint.x+cellW*.5,centerY=targetPoint.y-cellH*.5;cube(ctx,centerX-scaledW/2,centerY+scaledH/2,scaledW,scaledH,4*depthView.cargoScale,entry.cargoColor,depthView.cargoScale);}else if(!depthView.cargoAtCell&&op.cargoMode==='crane'&&depthView.cargoScale>0){const scale=depthView.cargoScale,w=10*scale,h=7*scale,centerX=aisleX+forkDepth,centerY=carY-forkDepth*.55;cube(ctx,centerX-w/2,centerY+h/2,w,h,4*scale,entry.cargoColor,scale);}else if(!depthView.cargoAtCell&&op.cargoMode==='cell')cube(ctx,targetPoint.x+cellW*.25,targetPoint.y-2,Math.max(7,cellW*.5),Math.max(5,cellH*.55),4,entry.cargoColor);}
    ctx.font='8px monospace';ctx.fillStyle=active?activityColor:'#63849a';ctx.fillText(op.label,12,top+108);ctx.fillStyle='#d8f3ff';ctx.fillText(active?`${entry.cargoType} → ${entry.name}`:(op.phaseLabel||''),55,top+108);ctx.fillStyle='#8fb0c2';ctx.fillText(active?`${op.detail} · 현재 ${Math.round(op.x)+1}열/${Math.round(op.y)+1}단`:'작업 대기',12,top+120);ctx.textAlign='right';ctx.fillStyle='#9fc5dd';ctx.fillText(active?`${op.elapsed.toFixed(1)} / ${op.total.toFixed(1)}초 · ${Math.round(op.progress*100)}%`:'',width-12,top+120);ctx.textAlign='left';
    if(active){const barX=12,barY=top+126,barW=width-24;ctx.fillStyle='#17334a';ctx.fillRect(barX,barY,barW,3);ctx.fillStyle=activityColor;ctx.fillRect(barX,barY,barW*op.progress,3);}
  });
}
