export const MotionState=Object.freeze({ACCELERATING:'Accelerating',CONSTANT:'ConstantSpeed',DECELERATING:'Decelerating',STOPPING:'Stopping',STOPPED:'Stopped'});

const positive=(value,fallback)=>Math.max(1e-6,Number.isFinite(Number(value))?Number(value):fallback);
export const standardMotionParameters=Object.freeze({targetSpeed:1,acceleration:.8,deceleration:1,jerk:1.5,motionProfile:'sCurve'});

export class KinematicMotion {
  constructor(config={},initial={}){this.position=Math.max(0,Number(initial.position)||0);this.velocity=Math.max(0,Number(initial.velocity)||0);this.acceleration=Number(initial.acceleration)||0;this.state=this.velocity>0?MotionState.ACCELERATING:MotionState.STOPPED;this.updateConfig(config);}
  updateConfig(config={}){this.config={...standardMotionParameters,...this.config,...config};this.config.targetSpeed=positive(this.config.targetSpeed,1);this.config.acceleration=positive(this.config.acceleration,.8);this.config.deceleration=positive(this.config.deceleration,1);this.config.jerk=positive(this.config.jerk,1.5);this.config.motionProfile=this.config.motionProfile==='trapezoidal'?'trapezoidal':'sCurve';return this;}
  step(dt,{distance=Infinity,blocked=false,speedFactor=1}={}){dt=Math.max(0,Number(dt)||0);if(!dt)return this.snapshot();const remaining=Math.max(0,distance-this.position),target=blocked?0:this.config.targetSpeed*Math.max(0,Number(speedFactor)||0),brakingDistance=this.velocity*this.velocity/(2*this.config.deceleration)+Math.abs(this.acceleration)*this.velocity/this.config.jerk,stopping=blocked||remaining<=brakingDistance,desiredAcceleration=stopping?-this.config.deceleration:this.velocity<target-1e-6?this.config.acceleration:this.velocity>target+1e-6?-this.config.deceleration:0;if(this.config.motionProfile==='sCurve'){const delta=Math.max(-this.config.jerk*dt,Math.min(this.config.jerk*dt,desiredAcceleration-this.acceleration));this.acceleration+=delta;}else this.acceleration=desiredAcceleration;const xNext=this.position+this.velocity*dt+.5*this.acceleration*dt*dt,vNext=Math.max(0,this.velocity+this.acceleration*dt);this.position=Math.min(distance,Math.max(this.position,xNext));this.velocity=this.position>=distance?0:vNext;if(this.position>=distance||blocked&&this.velocity<=1e-5){this.acceleration=0;this.state=MotionState.STOPPED;}else if(stopping)this.state=blocked?MotionState.STOPPING:MotionState.DECELERATING;else if(this.acceleration>1e-5)this.state=MotionState.ACCELERATING;else if(this.acceleration<-1e-5)this.state=MotionState.DECELERATING;else this.state=MotionState.CONSTANT;return this.snapshot();}
  snapshot(){return{position:this.position,velocity:this.velocity,acceleration:this.acceleration,state:this.state};}
}

export const motionConfigFor=item=>{const p=item?.parameters||{};return{targetSpeed:Number(p.targetSpeed??p.speed??p.travelSpeed??p.liftSpeed??.5),acceleration:Number(p.acceleration??.8),deceleration:Number(p.deceleration??p.acceleration??1),jerk:Number(p.jerk??1.5),motionProfile:Number(p.motionProfile??0)===1||p.motionProfile==='trapezoidal'?'trapezoidal':'sCurve'};};
export function kinematicTravelDuration(distance,config={},dt=.01){const motion=new KinematicMotion(config),limit=Math.max(10,Math.max(0,Number(distance)||0)/Math.max(.01,Number(config.targetSpeed)||1)*20);let elapsed=0;while(motion.position<distance&&elapsed<limit){motion.step(dt,{distance});elapsed+=dt;}return elapsed;}

export class DeterministicReliability {
  constructor(seed=1){this.seed=(Number(seed)||1)>>>0;this.elapsed=0;this.downRemaining=0;this.microRemaining=0;this.nextFailure=Infinity;this.nextMicro=Infinity;this.signature='';}
  random(){this.seed=(1664525*this.seed+1013904223)>>>0;return (this.seed+.5)/4294967296;}
  exponential(mean){return-mean*Math.log(Math.max(1e-12,1-this.random()));}
  updateConfig(parameters={}){const mtbf=Math.max(0,Number(parameters.mtbf)||0),micro=Math.max(0,Number(parameters.microStopInterval)||0),signature=`${mtbf}:${micro}`;if(signature!==this.signature){this.signature=signature;this.nextFailure=mtbf?this.elapsed+this.exponential(mtbf):Infinity;this.nextMicro=micro?this.elapsed+this.exponential(micro):Infinity;}this.parameters=parameters;}
  step(dt,parameters={}){this.updateConfig(parameters);this.elapsed+=dt;if(this.downRemaining>0)this.downRemaining=Math.max(0,this.downRemaining-dt);else if(this.elapsed>=this.nextFailure){this.downRemaining=Math.max(.01,Number(parameters.mttr)||60);this.nextFailure=this.elapsed+this.exponential(Math.max(.01,Number(parameters.mtbf)||3600));}if(this.microRemaining>0)this.microRemaining=Math.max(0,this.microRemaining-dt);else if(this.elapsed>=this.nextMicro){this.microRemaining=Math.max(.01,Number(parameters.microStopDuration)||.5);this.nextMicro=this.elapsed+this.exponential(Math.max(.01,Number(parameters.microStopInterval)||300));}return{available:this.downRemaining<=0&&this.microRemaining<=0,downRemaining:this.downRemaining,microRemaining:this.microRemaining};}
}
